name: Go
on:
  push:
    branches:
      - master
      - test_*
      - test-*
  pull_request:
    branches:
      - master
jobs:

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup protoc
      uses: arduino/setup-protoc@v1.1.2

    - name: Read Go versions
      run: echo "##[set-output name=go_version;]$(cat .github/versions/go)"
      id: go_versions

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ steps.go_versions.outputs.go_version }}
      id: go

    - name: Build
      run: go test -race ./...
